name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  header:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: header.svg
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          # Options
          user: sgloutnikov
          template: classic
          base: header

  repositories:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: repositories.svg
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          # Options
          user: sgloutnikov
          template: classic
          base: repositories

  activity_comm:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: activity_comm.svg
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          # Options
          user: sgloutnikov
          template: classic
          base: activity, community

  iso_calendar:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: iso_calendar.svg
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          # Options
          user: sgloutnikov
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  issue_pr_lang:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: issue_pr_lang.svg
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          # Options
          user: sgloutnikov
          template: classic
          base: ""
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, less
          plugin_languages_skipped: sgloutnikov/gloutnikov.com-pages, sgloutnikov/slaveya.ink-pages, sgloutnikov/sxm-tracker-client

  habits:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: habits.svg
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          # Options
          user: sgloutnikov
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_from: 300       # Use 200 events to compute habits
          plugin_habits_days: 21        # Keep only events from last 14 days
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          plugin_habits_skipped: sgloutnikov/gloutnikov.com-pages, sgloutnikov/slaveya.ink-pages, sgloutnikov/sxm-tracker-client
          
  achievements:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievements.svg
          # Options
          user: sgloutnikov
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C      # Display achievements with rank C or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
